tests - exceptiontester
testSimpleResume
	self assertSuccess: (ExceptionTester new runTest: #simpleResumeTest ) 